# --- ENERGÍA Y CONEXIÓN ---
# Aumenta la potencia de la señal para evitar interferencias
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Mantenemos el Deep Sleep desactivado para evitar que la pantalla se "duerma" demasiado
# CONFIG_ZMK_SLEEP=y

# --- RESPUESTA DE TECLAS ---
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# --- ZMK STUDIO (Edición en tiempo real) ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# --- CONFIGURACIÓN DE PANTALLA OLED ---
# Activar el soporte visual
CONFIG_ZMK_DISPLAY=y

# Tiempo de encendido: 90 segundos (1.5 min)
CONFIG_ZMK_IDLE_TIMEOUT=600000

CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_SSD1306_REVERSE_MODE=n
CONFIG_SSD1306_SH1106_COMPATIBLE=y

CONFIG_I2C=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN=y

CONFIG_PM=n



# --- BLUETOOTH ---
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- KEYS ---
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# --- ZMK STUDIO ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# --- DISPLAY (nice!view) ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN=y

# Tiempo antes de idle
CONFIG_ZMK_IDLE_TIMEOUT=90000




CONFIG_NICE_VIEW=y
