# --- BLUETOOTH / CONEXIÓN ---
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- RESPUESTA DE TECLAS ---
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# --- ZMK STUDIO ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# --- POWER / IDLE ---
# CONFIG_ZMK_IDLE_TIMEOUT=600000

# --- DISPLAY / POWER ---
CONFIG_LV_Z_MEM_POOL_SIZE=4608
CONFIG_ZMK_EXT_POWER=y
