# --- ENERGÍA Y CONEXIÓN ---
# Aumenta la potencia de la señal para evitar interferencias
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Mantenemos el Deep Sleep desactivado para evitar que la pantalla se "duerma" demasiado
# CONFIG_ZMK_SLEEP=y

# --- RESPUESTA DE TECLAS ---
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# --- ZMK STUDIO (Edición en tiempo real) ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# --- CONFIGURACIÓN DE PANTALLA OLED ---
# Activar el soporte visual
CONFIG_ZMK_DISPLAY=y

# Tiempo de encendido: 90 segundos (1.5 min)
CONFIG_ZMK_IDLE_TIMEOUT=90000

# Forzar el uso del diseño de pantalla estándar (iconos de batería, layer y BT)
# Si esto da error en GitHub, puedes borrar esta línea específica
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILTIN=y

# Activa el refresco de pantalla mediante la cola del sistema
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y
